# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - appsvcdb

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

      - name: Install EntityFrameworkTools
        run: |
             dotnet new tool-manifest
             dotnet tool install dotnet-ef

      - name: Generate EF Core Migration Script
        run: dotnet ef migrations script --idempotent --no-build --configuration Release --output ${{env.DOTNET_ROOT}}/sql/sql-script.sql --context DeploymentAppWithDb.Data.ProjectContext --project ${{ github.workspace }}/DeploymentAppWithDb/DeploymentAppWithDb.csproj

      - uses: actions/upload-artifact@v4
        with:
          name: ddl-updates
          path: ${{env.DOTNET_ROOT}}/sql/sql-script.sql

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
      
      - name: Login to Azure
        uses: azure/login@v4
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4055913D3C794A58BD44EBEC77705ABC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_39E68DA4DC52453A868C02E6EF44F263 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5E7C64C1E83D4FDB8B11488367A32323 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'appsvcdb'
          slot-name: 'Production'
          package: .

          
      - name: Azure SQL Deploy
        uses: Azure/sql-action@v4
        with:
          # The connection string, including authentication information, for the Azure SQL Server database.
          connection-string: ${{ secrets.SQL_CONNECTION_STRING }}
          # Path to the file used for this action. Supported file types are .sql, .dacpac, or .sqlproj.
          path: ./ddl-updates/sql-script.sql
          
